services:
  edge_device_1:
    image: muto_edge_device
    container_name: edge_device_1
    networks:
      - network

  edge_device_2:
    image: muto_edge_device
    container_name: edge_device_2
    networks:
      - network

  edge_device_3:
    image: muto_edge_device
    container_name: edge_device_3
    networks:
      - network

  sim:
    image: ghcr.io/eclipse-muto/multi-agent-sim:humble
    environment:
      - DISPLAY=novnc:0.0
    networks:
      - x11
    stdin_open: true
    tty: true
    depends_on:
      - novnc
  novnc:
    image: theasp/novnc:latest
    environment:
      - DISPLAY_WIDTH=1728
      - DISPLAY_HEIGHT=972
    ports:
      - "8080:8080"
    networks:
      - x11
networks:
  network:
    driver: bridge
  network2:
    driver: bridge
  network3:
    driver: bridge
  network4:
    driver: bridge
  x11:
