FROM ros:humble-ros-core

RUN apt-get update && apt-get install -y \
    ros-humble-rmw-zenoh-cpp \
    netcat \
    && rm -rf /var/lib/apt/lists/*

COPY config/zenoh_router_config.json5 /etc/zenoh/router_config.json5
ENV ZENOH_ROUTER_CONFIG_URI=/etc/zenoh/router_config.json5

SHELL ["/bin/bash", "-c"]
CMD source /opt/ros/humble/setup.bash && ros2 run rmw_zenoh_cpp rmw_zenohd
